apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-htge
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-srcu-tenant/rhtap-demo-app/hacbs-test-project-htge@sha256:a3857d617f0e604135b9f9be49181d999505a7a24567ecf4d8ffc1231b8ba3b7
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
